### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by juntyr** [apertus-open-source-cinema/sz3-rs#3]
First of all, thank you very much for creating the sz3-rs Rust wrapper! I've been using for almost a year now and it has helped me greatly.

As part of my usage, which includes compiling to wasm32, I've been maintaining an active fork (https://github.com/apertus-open-source-cinema/sz3-rs/compare/main...juntyr:sz3-rs:wasmi) that upgraded SZ3 (similar to #2), but includes the original SZ3 repo as a submodule (actually, a fork (https://github.com/szcompressor/SZ3/compare/master...juntyr:SZ3:sz3-rs) of the original repo, so that I can track any changes I make to the SZ3 source in a clean diff, e.g. to support wasm) for easier maintainability, makes OpenMP support optional, and fixes a few bugs on the C++ and Rust side.

As #2 has been open for a while without response, I wanted to first ask if this repo and crate are still being maintained so that submitting a PR would be worth it and would result in a new crates.io release afterwards.

Otherwise, I also wanted to offer to take over the maintenance of this crate, as my PhD research focuses on compression and maintaining this crate is in my own interest.

**Comment by rroohhh** [comment]
Hi, 
thank you for taking interest in this crate. 
We are still paying attention to this repository and if you submit a PR I will take a look at it. 
I am not sure what you are talking about wrt crates.io, as this crate was never published there, although I am not opposed to that.

As for tracking your fork of SZ3, I am not too keen on it, do you envision your changes to support wasm to make it upstream?
